### ISSUE TITLE
Support of django versions

### ISSUE THREAD

**Issue by Treverix** [divio/djangocms-admin-style#306] opened 2016-03-11 09:39 UTC
I recommend that you make it more clear that V1.10 is not compatible with older versions of django anymore. It really needs django 1.9 - at least the admin styles of django 1.9. Otherwise the change forms don't really look well (submit row, inlines)

Workaround for django 1.8: from django 1.9, copy `forms.css` to your local `static/admin/css` folder (create, if not existing yet) and fix the style for `.submit-row`:

```
.submit-row {
    padding: 12px 14px !important;
    margin: 0 0 20px;
    background: #f8f8f8;
    border: 1px solid #eee;
    border-radius: 4px;
    text-align: right;
    overflow: hidden;
}
```

(padding needs an `!important`)

**Comment by lory87** [comment] 2016-04-13 06:59
@Treverix can you provide us please a screenshot how submit row looks like? Thank you in advance.

**Comment by lory87** [comment] 2016-04-18 08:38
gentle ping @Treverix can you provide us a screenshot please?

**Comment by Treverix** [comment] 2016-04-18 09:22
Sorry, here's the pong :)

This screenshot shows how v1.10 looks on django 1.8x on my machine. It shows an inline and the submit row.

![image](https://cloud.githubusercontent.com/assets/1685275/14599430/8cda0054-0557-11e6-878d-dbbb6287ab57.png)

**Comment by lory87** [comment] 2016-04-18 09:51
@Treverix thank you for your screenshot. I tested it as well with an inline app, django version 1.8.8 and djangocms-admin-style 1.1.0. It looks nice. I enclosed a screenshot as well and I can't reproduce. Can you please provide me your pip freeze to get more details?

![screen shot 2016-04-18 at 11 47 58](https://cloud.githubusercontent.com/assets/2270884/14600235/dd91f9d0-055b-11e6-83af-57b95c0e751d.png)

**Comment by Treverix** [comment] 2016-04-18 10:19
I've just upgraded from 1.8.6 to 1.8.8. hoping that would already solve the issue, but unfortunately not. Here is one more screenshot, with dev tools open. forms.css is the one from django itself. I double-checked that 'djangocms_admin_style' is just before 'django.contrib.admin' in the INSTALLED_APPS section.

The pip freeze is added as a file.

![image](https://cloud.githubusercontent.com/assets/1685275/14600949/9293674e-055f-11e6-84b7-8cf7237142b6.png)

[pipfreeze.txt](https://github.com/divio/djangocms-admin-style/files/223529/pipfreeze.txt)

**Comment by lory87** [comment] 2016-04-18 11:14
@Treverix thank you for your infos. I pushed some changes to master branch. Can you please check if the issue still appears?

**Comment by Treverix** [comment] 2016-04-18 15:09
Here's what it looks now. The remaining issue is the inline :) It wasn't part of the issue - but I think, it's not expected like this:

![image](https://cloud.githubusercontent.com/assets/1685275/14609021/576f0d84-0588-11e6-86de-d0aa4f0f0caa.png)

**Comment by lory87** [comment] 2016-04-18 15:14
@Treverix I see that submit row is fixed and looks nice now. Inline-groups are not expected to work like this. They should not be wrapped with submit-row.

**Comment by Treverix** [comment] 2016-04-18 15:28
They are not wrapped. This is just a 'simple' changeview with some inlines. Like this one - which ist from a different model but it looks the same:

```
@admin.register(ClassificationClass)
class ClassificationClassAdmin(admin.ModelAdmin):
    list_select_related = True
    list_display = ('code', 'description', '_items')
    fields = ('code', 'description', )
    ordering = ('code',)
    inlines = (ClassificationItemInline, )

```

**Comment by lory87** [comment] 2016-04-18 15:42
@Treverix can you provide me a html snippet that I can reproduce on which element this borders are?

**Comment by Treverix** [comment] 2016-04-18 15:51
Here you go. It's class inline-group. Make border !important on your class for a quick fix :)

![image](https://cloud.githubusercontent.com/assets/1685275/14610434/37a20c08-058e-11e6-835d-364403dcaccf.png)

**Comment by lory87** [comment] 2016-04-18 15:56
@Treverix Thank you very much. Pushed some changes to master branch. Thank you for your feedback.

**Comment by lory87** [comment] 2016-04-19 09:20
@Treverix Can I close this issue?

**Comment by Treverix** [comment] 2016-04-19 09:38
Yes, fine with me :) I hope it still works with django 1.9.x, because the root cause was that they changed some styles. So I wait for the next release of this app.

**Comment by lory87** [comment] 2016-04-19 09:50
@Treverix Great thanks for your feedback. We will soon do a release.

**Closed by lory87** 2016-04-19 09:50 UTC

**Comment by Treverix** [comment] 2016-04-28 08:22
Thanks for the release!! It solved a lot of problems we had with the style. Looks great now!

**Comment by FinalAngel** [comment] 2016-04-28 09:15
you are very welcome @Treverix thanks goes to @lory87
