### ISSUE TITLE
Avoiding use of !Important

### ISSUE THREAD

**Issue by Nekmo** [divio/djangocms-admin-style#336] opened 2016-04-30 12:39 UTC
I'm trying to integrate some bootstrap elements in the Admin and DjangoCMS theme is giving me problems.

![amazon_xenoblade10](https://cloud.githubusercontent.com/assets/740106/14935844/a8cec14a-0ee0-11e6-8d11-f6f6f0d76767.png)

Some examples:

```
form button {
    border-radius: 3px!important;
    width: auto!important;
}

button {
    color: #555!important;
    font-size: 12px!important;
}
```

And more. I think using !Important is a bad idea. 

Thanks!

**Comment by lory87** [comment] 2016-04-30 22:04
Hi @Nekmo 
Thank you for your feedback. We are aware of this issue and we are working on a cleanup. Will let you know when we are done with the changes.

**Comment by radiac** [comment] 2016-05-17 22:26
On a related note because the djangocms admin styles are added in the `{% block extrahead %}`, you can't override them from the `{% block extrastyle %}` as it comes before. Obviously it's something you can work around once you realise the problem, but may be helpful to move the `djangocms-admin.css` link before the `extrastyle` include to avoid confusion.

**Comment by FinalAngel** [comment] 2016-05-18 06:10
@vxsx something to consider for the next release?

**Comment by evenicoulddoit** [comment] 2016-06-06 09:41
I was literally about to make the exact same issue as this.
The [changes since 1.9 support](https://github.com/divio/djangocms-admin-style/compare/3557d06f5fa48ee73cb1158abf4ef4cd5fd0f4a8...a1d4b80c8066b67438b255026f0d4290bd3df825) has made overriding the styles (e.g. to add select2 support) really difficult.

**Comment by marksweb** [comment] 2016-06-14 11:38
On a related note to the `!important` styles, the `width: calc(100% - 112px)!important` on date fields and the `max-width: none !important` that effects select boxes make inputs look pretty hideous. 

![screen shot 2016-06-14 at 12 35 52](https://cloud.githubusercontent.com/assets/1461191/16041334/a5fb482a-322c-11e6-98e2-f8ba49dc8a62.png)


Is there a reason they've got these attributes? Could the date field width not be much less than 100% & the `max-width: none` just be removed?

**Comment by FinalAngel** [comment] 2016-06-14 12:14
@marksweb creating the styles to reformat the admin is in general a beast. We just recently added integration tests that automatically create screenshots (you have to consider differences in django 1.8 and 1.9) plus changes can affect multiple addons differently.

We are keeping an eye on it, though our resources are a bit limited for the next weeks. I'd welcome help on improving / extending the tests.

**Comment by marksweb** [comment] 2016-06-14 12:29
@FinalAngel of course, sorry, my comment wasn't very sympathetic to the considerable job this is, was it!?

I'm not sure I'll get any input from our design team, but I might fork the repo & tweak a few bits with a stylesheet override. That way if I get anything worthwhile changed, you could take a look.

How are you running the screenshot based tests? It's been on the backburner for me for a little while, the last I used was PhantomJS & Selenium for CSS regression.

**Comment by FinalAngel** [comment] 2016-06-14 12:59
@marksweb no offends taken, just a general feedback :)

The screenshot integration tests run with Docker and the Makefile: https://github.com/divio/djangocms-admin-style#integration-tests

Simply run ``make run18`` and then ``make test18``. The same is available for Django 1.9. The best practice there would be, to create more tests in https://github.com/divio/djangocms-admin-style/tree/master/screenshots/reference and then overwrite and see how it affects the system.

**Comment by vstoykov** [comment] 2016-07-01 15:25
My suggestion about solving the issue with `!important` is just to remove it everywhere and all selectors to be prefixed with `.djangocms-admin-style`.
If the selector is the same as in django theme because of the extra class in front it will be stronger and will use the styles from `djangocms-admin-style`.

By this way all 3th parties can provide styles that will work only if `djangocms-admin-style` is used or not. The same way as the `flat` theme for Django (from Django 1.9 and up).

**Comment by vxsx** [comment] 2016-07-02 09:34
@vstoykov that's part of the plan. Given that now there are css regression tests available, it will be easier to implement the changes. No ETA, but very soon :)

**Comment by benzkji** [comment] 2019-09-05 07:32
ETA ? ;-)

**Comment by FinalAngel** [comment] 2020-08-21 07:36
I will close this now until someone wants to tackle this issue, it's not simple and requires a substantial rewrite.

**Closed by FinalAngel** 2020-08-21 07:36 UTC
